### ISSUE TITLE
Reimplement DDs using C/C++

### ISSUE THREAD

**Issue by cjdrake** [cjdrake/pyeda#105]
Most likely using CUDD.

**Comment by johnyf** [comment]
A suggestion would be to use the [`dd`](https://github.com/johnyf/dd) package. It is written in pure Python, and includes several standard algorithms, including reordering by sifting (CUDD's default).

A timing comparison [using the N-queens problem](https://github.com/johnyf/dd/tree/f414934f3070715746d03c2c9dc25035e7a3eeeb/examples) produces the result below. In these runs, reordering was not used. In the future, reordering will be automatically invoked. (For example, the 9 queens instance results in a shared ROBDD that reaches `>10**6` nodes).

It is planned to create (optional) bindings from `dd` to a C package, so that the user code can still be developed in Python (easy to debug and instrument), and then be used w/o changes for large problems. This will avoid duplication of effort.

A minor point is that `dd` is written in Python 2.7, but it shouldn't be too difficult to run it in Python 3 (e.g., using `six`).

![comparison](https://cloud.githubusercontent.com/assets/3135273/8028027/36d020f4-0d59-11e5-83ee-67c0b5a608fd.png)

**Comment by cjdrake** [comment]
Ioannis, thanks for the suggestion. This looks like a really neat library :+1:

**Comment by johnyf** [comment]
Thanks, `dd == 0.1.1` has been released, and it includes (optional) Cython bindings to CUDD and BuDDy. The bindings look (almost) the same with the pure-Python interface (the one that automates reference counting), so they can be swapped w/o changes to user code. This allows distributing a pure-Python version, and deploying CUDD for problems whose size requires it.
