### ISSUE TITLE
Python 3.11 Support 

### ISSUE THREAD

**Issue by swpinkerton** [cjdrake/pyeda#177]
Would it be possible to get a release for Python 3.11?
The main issue I've come across, is addressed in #172 and has been fixed in the commit `136625017bc4bc442437bb9c05b4ed38e13858a4` 

I also get an issue with line 329 from pyeda/pyeda/boolalg/boolfunc.py, as the doctest passes a different type of Variable as checked by `if isinstance(v, Variable)`. The line needs to be adapted to check for v being an instance of `pyeda.boolalg.expr.Variable` aswell

**Comment by cjdrake** [comment]
Does anybody want to volunteer? This project needs some new blood, because I'm obviously not keeping up with maintenance. I started looking into this the other day, and realized I'm *way* behind the Python packaging standards. Now there's `.toml` files, and I haven't read any of that documentation. All the continuous integration stuff is busted now. I still have all my PyPI login info, so I can grant ownership/maintenance permission to someone if they want to do some release work.
